create database GESTAO

CREATE TABLE FUNCIONARIO(
ID_FUNCIONARIO INT PRIMARY KEY,
NOME VARCHAR(150),
IDADE INT,
DATA_NASC DATE,
CELULAR VARCHAR(13),
SENHA VARCHAR(20),
ENDERECO VARCHAR(180),
COD_CARGO INT,
)

CREATE TABLE CARGO(
ID_CARGO INT PRIMARY KEY,
GERENTE INT,
CORDENADOR INT,
ATENDENTE  INT,
)

CREATE TABLE CLIENTE(
ID_CLIENTE INT PRIMARY KEY,
NOME VARCHAR(150),
IDADE INT,
DATA_NASC DATE,
CELULAR VARCHAR(13),
EMAIL VARCHAR(50),
ENDERECO VARCHAR(180),
)

CREATE TABLE PEDIDO(
ID_PEDIDO INT PRIMARY KEY,
COD_CLIENTE INT,
COD_FUNCIONARIO INT,
COD_FORMA_PAGAMENTO INT,
VALOR_TOTAL FLOAT,
DATA_PEDIDO DATE,
)

CREATE TABLE PEDIDO_PRODU(
COD_PEDIDO INT,
COD_PRODUTO INT,
PRECO_UNI FLOAT,
QUANT INT,
PRECO_ITEM_TOTAL FLOAT,
)

CREATE TABLE PRODUTO(
ID_PRODUTO INT PRIMARY KEY,
NOME VARCHAR(70),
CATEGORIA VARCHAR(90),
PRECO FLOAT,
ESTOQUE INT,
)

CREATE TABLE FORMA_PAGAMENTO(
ID_FORMA_PAG INT PRIMARY KEY,
PIX INT,
AVISTA INT,
CREDITO INT,
DINHEIRO INT,
)



ALTER TABLE FUNCIONARIO
ADD CONSTRAINT FK_FUNC_CARGO
FOREIGN KEY (COD_CARGO) REFERENCES CARGO (ID_CARGO)

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PED_FUNC
FOREIGN KEY (COD_FUNCIONARIO) REFERENCES FUNCIONARIO (ID_FUNCIONARIO)

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PED_CLIE
FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PED_PAG
FOREIGN KEY (COD_FORMA_PAGAMENTO) REFERENCES FORMA_PAGAMENTO (ID_FORMA_PAG)

ALTER TABLE PEDIDO_PRODU
ADD CONSTRAINT FK_PEDIDO_P
FOREIGN KEY (COD_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO)
 
ALTER TABLE PEDIDO_PRODU
ADD CONSTRAINT FK_PEDIDO_PROD
FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)

SELECT * FROM CLIENTE

 INSERT INTO CLIENTE (ID_CLIENTE, NOME, IDADE, DATA_NASC, CELULAR,EMAIL,ENDERECO)
   VALUES (1,'Klauber Lais ',19,'2004-02-17', '9888888', '@GMAIL.COM','12 maria seu c#' )





